name: whereismycar
description: Where is my car?
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: ^7.1.0
  dartz: ^0.10.1
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_flavor: ^3.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  logger: ^1.1.0
  path: any
  retrofit_generator: ^6.0.0+3
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.3.0

  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  intl_utils: ^2.7.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Translation
  arb_dir: lib/app/utils/translations/l10n
  output_dir: lib/app/utils/translations/generated
