name: whereismycar
description: Where is my car?
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^7.1.0
  flutter_bloc: ^8.1.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  logger: ^1.1.0
  intl: ^0.18.0
  dartz: ^0.10.1
  json_serializable: ^6.5.4
  retrofit_generator: ^6.0.0+3
  json_annotation: ^4.7.0
  flutter_flavor: ^3.1.1
  gap: ^3.0.0


dev_dependencies:
  build_runner: ^2.3.0
  injectable_generator: ^2.1.3
  auto_route_generator: ^7.0.0
  intl_utils: ^2.7.0


  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Translation
  arb_dir: lib/app/utils/translations/l10n
  output_dir: lib/app/utils/translations/generated